#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
# Pylint Path is Micky's local path, feel free to change in PR 

PYLINT = "c:\users\micky\appdata\local\programs\python\python310\lib\site-packages\pylint" 
ESLINT="client/node_modules/.bin/eslint"
pwd

if [[ ! -x "$PYLINT" ]]; then
	  printf "\t\033[41mPlease install Pylint\033[0m (pip install pylint)\n"
	    exit 1
    fi

    STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".py$"))

    echo "Checking ${#STAGED_FILES[@]} staged files for Pylint Errors..."

    if [[ "$STAGED_FILES" = "" ]]; then
	      exit 0
      fi

      $PYLINT "${STAGED_FILES[@]}" --fix --rcfile /.lint/.pylintrc --load-plugins 

      PYLINT_EXIT="$?"

      if [[ "${PYLINT_EXIT}" == 0 ]]; then
	        printf "\n\033[42mPYLINT PASSED\033[0m\n"
	else
		  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix pylint errors and try again\n"
		    exit 1
	    fi

	    exit $?

if [[ ! -x "$ESLINT" ]]; then
	  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
	    exit 1
    fi

    STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$"))

    echo "Checking ${#STAGED_FILES[@]} staged files for ESLint Errors..."

    if [[ "$STAGED_FILES" = "" ]]; then
	      exit 0
      fi

      $ESLINT "${STAGED_FILES[@]}" --fix

      ESLINT_EXIT="$?"

      # Re-add files since they may have been fixed
      git add "${STAGED_FILES[@]}"

      if [[ "${ESLINT_EXIT}" == 0 ]]; then
	        printf "\n\033[42mESLINT PASSED, COMMIT SUCCEEDED\033[0m\n"
	else
		  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
		    exit 1
	    fi

	    exit $?
