# Generated by Django 3.2.12 on 2022-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0002_auto_20220330_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='histogram',
            name='isLive',
            field=models.BooleanField(default=False),
        ),
    ]
