# Generated by Django 3.2.12 on 2022-04-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0003_histogram_islive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histogram',
            name='isLive',
        ),
    ]
