# This workflow:
# - Runs the BE and FE
# - Runs unit tests on the BE
# - Runs `curl` on the FE just to make sure it started up

name: TestBEandFE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: 3.6.9
  NODE_VERSION: 16
  FE_ENDPOINT: http://localhost:3000/

jobs:
  runBEandFE:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install python dependencies
        working-directory: server
        run: |
          pip install --upgrade pip
          pip install -r dependencies.txt

      - name: Linting -- Python black
        working-directory: server
        run: black . --check

      - name: BE -- Generate secret key and security file
        working-directory: server
        run: python tests/genSecurityFile.py --debug True

      - name: BE -- Generate live database
        working-directory: server
        run: python manage.py migrate --database=live

      - name: Run BE in background
        working-directory: server
        run: |
          daphne nEDM_server.asgi:application &
          sleep 1

      - name: BE -- Unit tests
        working-directory: server
        run: pytest tests

      - name: Set up Node js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node dependencies
        working-directory: client
        run: npm ci

      - name: Linting -- Eslint
        working-directory: client
        run: npm run lint

      - name: FE -- Get schema from FE and generate Tsx file
        working-directory: client
        run: npm run generate

      - name: FE -- Run FE in background
        working-directory: client
        run: |
          npm start &
          sleep 1

      - name: FE -- Ping FE
        working-directory: client
        run: curl ${{ env.FE_ENDPOINT }} -I
